name: "Voltalis Intégration"
version: "stable"
slug: "voltalis-stable"
description: "Intégration Voltalis en Go exposant des entités dynamiques via l'API Home Assistant"
startup: "services"
homeassistant_api: true
hassio_api: true
boot: "auto"
arch:
    - aarch64
    - amd64
map:
    - config:rw
options:
    mqtt_url: "localhost:1883"
    mqtt_password: ""
    voltalis_login: ""
    voltalis_password: ""
schema:
    mqtt_url: str
    mqtt_password: str?
    voltalis_login: str
    voltalis_password: str
image: "ghcr.io/francois76/voltalis"