name: Build Voltalis Addon

on:
  push:
    branches:
      - main
      - nightly

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        run: |
          BRANCH=${GITHUB_REF_NAME}
          IMAGE="ghcr.io/${{ github.repository_owner }}/voltalis"
          TAG="nightly"
          if [ "$BRANCH" = "main" ]; then
            TAG="stable"
          fi
          docker buildx build --platform linux/amd64,linux/arm64 \
            -t $IMAGE:$TAG --push voltalis
